desired_caps:
  A10s:
    platformName: 'Android'
    deviceName: 'A10s'
    udid: 'R9HN70VWB5J'
    platformVersion: '12'
    automationName: 'UiAutomator2'
    appPackage: 'com.samanpr.blu.dev'
    appActivity: 'com.samanpr.blu.presentation.BaseActivity'

server_url: 'http://127.0.0.1:4723/wd/hub'
implicit_wait: 10
